import './globals.css'

export const metadata = {
  title: 'midPoint',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
        <nav className='flex justify-between p-4'>
          <h1>logo</h1>
          <ul className='flex'>
            <li className='px-2'>
              <a href="./">Home</a>
            </li>
            <li className='px-2'>
              <a href="about">About</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
